# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_geofield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=30, verbose_name='Parti No')),
                ('fish_type', models.CharField(max_length=30, verbose_name='Bal\u0131k Cinsi')),
            ],
        ),
        migrations.CreateModel(
            name='Box_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('temp', models.FloatField(default=0.0, verbose_name='Kasa S\u0131cakl\u0131\u011f\u0131')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Box', verbose_name='Kasa')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u015eirket Ad\u0131')),
                ('address', models.TextField(blank=True, max_length=50, null=True, verbose_name='Adres')),
                ('tax_id', models.CharField(max_length=30, verbose_name='Vergi No')),
                ('score', models.FloatField(default=0.0, verbose_name='Puan\u0131')),
            ],
        ),
        migrations.CreateModel(
            name='Fish_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'That fish type is already saved.'}, max_length=30, verbose_name='Bal\u0131k Cinsi')),
                ('slug', models.CharField(max_length=30, verbose_name='K\u0131sa isim')),
                ('icon', models.CharField(default='fa-users', max_length=15, verbose_name='Icon')),
                ('color', models.CharField(default='bg-yellow', max_length=10, verbose_name='Renk')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Fishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Av Ba\u015flang\u0131c\u0131')),
                ('end_date', models.DateTimeField(verbose_name='Av Biti\u015fi')),
                ('depot_level', models.FloatField(default=0.0, verbose_name='Depo Seviyesi')),
                ('depot_temp', models.FloatField(default=0.0, verbose_name='Depo S\u0131cakl\u0131\u011f\u0131')),
                ('lot_no', models.CharField(max_length=30, verbose_name='Parti No')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Olu\u015fturulma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django_geofield.fields.GeoPositionField(db_index=True, max_length=32)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Olu\u015fturulma Tarihi')),
                ('fishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Fishing', verbose_name='Av')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u0130sim')),
                ('surname', models.CharField(max_length=30, verbose_name='Soyisim')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Uyru\u011fu')),
                ('nat_id', models.CharField(max_length=12, unique=True, verbose_name='TC No')),
                ('gender', models.IntegerField(choices=[(1, 'Belirtilmemi\u015f'), (2, 'Kad\u0131n'), (3, 'Erkek')], default=1, verbose_name='Cinsiyet')),
                ('address', models.TextField(blank=True, max_length=50, null=True, verbose_name='Adres')),
                ('profile_picture', models.ImageField(default='profile_pictures/profile.png', null=True, upload_to='profile_pictures/', verbose_name='Profil Foto\u011fraf\u0131')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='A\xe7\u0131klama')),
                ('total_workday', models.IntegerField(default=0, verbose_name='Toplam i\u015f g\xfcn\xfc')),
                ('total_workhour', models.IntegerField(default=0, verbose_name='Toplam i\u015f saati')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'That personnel type is already saved.'}, max_length=30, verbose_name='Personel Tipi')),
                ('slug', models.CharField(max_length=30, verbose_name='K\u0131sa isim')),
                ('icon', models.CharField(default='fa-users', max_length=15, verbose_name='Icon')),
                ('color', models.CharField(default='bg-yellow', max_length=10, verbose_name='Renk')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False, verbose_name='Silinmi\u015f')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(default='vessel_pictures/vessel.png', null=True, upload_to='vessel_pictures/', verbose_name='Tekne Foto\u011fraf\u0131')),
                ('fishing_license', models.ImageField(null=True, upload_to='licenses/', verbose_name='Av lisans\u0131')),
                ('hull_length', models.FloatField(default=0.0, verbose_name='Tekne Boyu')),
                ('score', models.FloatField(default=0.0, verbose_name='Puan\u0131')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Olu\u015fturulma Tarihi')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='personnel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fishing.Personnel_type', verbose_name='Personel Tipi'),
        ),
        migrations.AddField(
            model_name='fishing',
            name='personnels',
            field=models.ManyToManyField(to='fishing.Personnel'),
        ),
    ]
