# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0003_auto_20180210_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='rfid_no',
            field=models.CharField(default='', max_length=30, verbose_name='RFID no'),
        ),
    ]
