# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0004_box_rfid_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='lot_no',
        ),
        migrations.AddField(
            model_name='box',
            name='fish_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing.Fish_type', verbose_name='Bal\u0131k Cinsi'),
        ),
        migrations.AlterField(
            model_name='box',
            name='fishing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing.Fishing', verbose_name='Av'),
        ),
    ]
