# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0005_auto_20180210_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing.Company', verbose_name='\u015eirket'),
        ),
    ]
