# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0006_box_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishing',
            name='vessel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing.Vessel', verbose_name='Tekne'),
        ),
    ]
