# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0007_fishing_vessel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
