# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0008_auto_20180210_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u0130sim')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Olu\u015fturulma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='fishing',
            name='harbor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing.Harbor', verbose_name='Liman'),
        ),
    ]
