# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0009_auto_20180210_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishing',
            name='co2_emmission',
            field=models.FloatField(default=0.0, verbose_name='CO2 sal\u0131n\u0131m\u0131'),
        ),
    ]
